server:
  port: 9004

app:
  storage:
    local:
      path: localDirectory

spring:
  application:
    name: file-module
  datasource:
    url: jdbc:postgresql://localhost:5437/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect