server:
  port: 9004

app:
  storage:
    local:
      path: localDirectory

spring:
  application:
    name: file-module
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/oauth2-demo-realm

#logging:
#  level:
#    org.springframework.security: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui.html