package pl.app.common.shared.authorization;

public enum PermissionName {
    ACCOMMODATION_READ,
    ACCOMMODATION_WRITE,
    ACCOMMODATION_AVAILABILITY_READ,
    ACCOMMODATION_AVAILABILITY_WRITE,
    ACCOMMODATION_PRICE_READ,
    ACCOMMODATION_PRICE_WRITE,
    ACCOMMODATION_PRICE_POLICY_READ,
    ACCOMMODATION_PRICE_POLICY_WRITE,
    ACCOMMODATION_TYPE_READ,
    ACCOMMODATION_TYPE_WRITE,

    AMENITY_READ,
    AMENITY_WRITE,

    GUEST_READ,
    GUEST_WRITE,

    ORGANIZATION_READ,
    ORGANIZATION_WRITE,

    PROPERTY_READ,
    PROPERTY_WRITE,

    REGISTRATION_READ,
    REGISTRATION_WRITE,
    REGISTRATION_FOLIO_READ,
    REGISTRATION_FOLIO_WRITE,

    RESERVATION_READ,
    RESERVATION_WRITE,
    RESERVATION_FOLIO_READ,
    RESERVATION_FOLIO_WRITE,
    RESERVATION_PAYMENT_POLICY_READ,
    RESERVATION_PAYMENT_POLICY_WRITE,

    USER_READ,
    USER_WRITE,
}
