version: '3'
services:
  postgres-db:
    container_name: 'postgres-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5435:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  mail-db:
    container_name: 'mail-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5437:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4:7.4'
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass@word123
    ports:
      - '9050:80'
  axon-server:
    container_name: 'axon-server'
    image: 'axoniq/axonserver:latest-jdk-17-dev'
    restart: unless-stopped
    ports:
      - '8024:8024'
      - '8124:8124'
  keycloak:
    container_name: 'keycloak'
    image: 'bitnami/keycloak:22.0.1'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '8443:8443'
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_MANAGEMENT_USER=user
      - KEYCLOAK_MANAGEMENT_PASSWORD=password

      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=postgres
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_JDBC_PARAMS=connectTimeout=30000
      - KEYCLOAK_ENABLE_HTTPS=false
  keycloak-db:
    container_name: 'keycloak-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres


volumes:
  postgres-db: