version: '3'
services:
  postgres-db:
    container_name: 'postgres-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5435:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  mail-db:
    container_name: 'mail-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5437:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4:7.4'
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass@word123
    ports:
      - '9050:80'

volumes:
  postgres-db:
  mail-db: